# Generated by Django 4.1.2 on 2022-10-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
