# Generated by Django 3.1.3 on 2022-10-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgFile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
