# Generated by Django 4.1.2 on 2022-10-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sales_pname_sales_scode_sales_sname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=10)),
                ('sname', models.TextField(max_length=40, null=True)),
                ('qty', models.IntegerField()),
                ('amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_date', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
    ]
