# Generated by Django 3.1.3 on 2022-10-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20221019_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imgFile',
        ),
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
