# Generated by Django 3.1.3 on 2022-10-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20221019_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountrate',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitprice',
            field=models.IntegerField(),
        ),
    ]
